/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admission;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author abrar
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    String user;
    public admin() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    public void update()
    {
        try {
            try 
            {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) 
            {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/std_info","root","");
            
            String sql = "SELECT * FROM `std`";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while(rs.next())
            {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/admission","root","");
                
                if(rs.getString("pymA").equals("900"))
                {
                    String sq = "INSERT INTO `aunit`(`name`) VALUES (?)";
                    PreparedStatement ps = conn.prepareStatement(sq);
                    System.out.println("OK A");
                    ps.setString(1,rs.getString("name"));
                    ps.executeUpdate();
                }
                if(rs.getString("pymB").equals("900"))
                {
                    String sq = "INSERT INTO `bunit`(`name`) VALUES (?)";
                    PreparedStatement ps = conn.prepareStatement(sq);
                    ps.setString(1,rs.getString("name"));
                    System.out.println("OK B");
                    ps.executeUpdate();
                }
                 if(rs.getString("pymC").equals("900"))
                {
                    String sq = "INSERT INTO `cunit`(`name`) VALUES (?)";
                    PreparedStatement ps = conn.prepareStatement(sq);
                    ps.setString(1,rs.getString("name"));
                    System.out.println("OK C");
                    ps.executeUpdate();
                }
                 if(rs.getString("pymD").equals("600"))
                {
                    String sq = "INSERT INTO `dunit`(`name`) VALUES (?)";
                    PreparedStatement ps = conn.prepareStatement(sq);
                    ps.setString(1,rs.getString("name"));
                    System.out.println("OK D");
                    ps.executeUpdate();
                }
                  if(rs.getString("pymE").equals("900"))
                {
                    String sq = "INSERT INTO `eunit`(`name`) VALUES (?)";
                    PreparedStatement ps = conn.prepareStatement(sq);
                    ps.setString(1,rs.getString("name"));
                    System.out.println("OK E");
                    ps.executeUpdate();
                }
            }
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex+" error in unit selection");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAdminUser = new javax.swing.JTextField();
        txtAdminPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Log in");
        setFocusable(false);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("USER NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 31, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtAdminUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAdminUser.setForeground(new java.awt.Color(153, 153, 153));
        txtAdminUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtAdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 28, 177, -1));

        txtAdminPass.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtAdminPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAdminPass.setToolTipText("");
        jPanel1.add(txtAdminPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 177, -1));

        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 108, 37));

        btnLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin1.setText("Log in (Update)");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 150, 160, 37));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 480, 220));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jahangirnagar University");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 540, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Undergraduate Admission 2022");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 500, 80));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admission/logo 160px.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 160, 160));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 680));

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 680));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("ADMIN LOG IN");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

         user = txtAdminUser.getText();
        String pass = txtAdminPass.getText();

        if (user.equals("") || pass.equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Username or Password field is empty");
        } 
        else 
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"error2");
            }

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/admin_info", "root", "");
                PreparedStatement st;
                System.out.println(user);
                String sql = "SELECT  password FROM admin WHERE username = ?";
                st = con.prepareStatement(sql);
                st.setString(1,user);
                ResultSet rs = null;
                
                rs=st.executeQuery();

                if (rs.next()) {
                    String mp = rs.getString("password");
                    if (mp.equals(pass)) {
                        
                        
                        try 
                        {
                            Desktop d = Desktop.getDesktop();
                            d.browse(new URI("http://localhost/phpmyadmin/index.php?route=/sql&db=std_info&table=std&pos=0"));
                        } catch (URISyntaxException | IOException ex) {
                            JOptionPane.showMessageDialog(null,ex);
                        }
                    } else {
                        
                        JOptionPane.showMessageDialog(null,"INCORRECT CREDENTIALS","WARNING !!!",JOptionPane.WARNING_MESSAGE);

                    }
                    

                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Password", "Warning !!!", JOptionPane.WARNING_MESSAGE);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }

        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new Login().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        user = txtAdminUser.getText();
        String pass = txtAdminPass.getText();

        if (user.equals("") || pass.equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Username or Password field is empty");
        } 
        else 
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"error2");
            }

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/admin_info", "root", "");
                PreparedStatement st;
                System.out.println(user);
                String sql = "SELECT  password FROM admin WHERE username = ?";
                st = con.prepareStatement(sql);
                st.setString(1,user);
                ResultSet rs = null;
                
                rs=st.executeQuery();

                if (rs.next()) {
                    String mp = rs.getString("password");
                    if (mp.equals(pass)) {
                        
                        update();
                        try 
                        {
                            Desktop d = Desktop.getDesktop();
                            d.browse(new URI("http://localhost/phpmyadmin/index.php?route=/sql&db=std_info&table=std&pos=0"));
                        } catch (URISyntaxException | IOException ex) {
                            JOptionPane.showMessageDialog(null,ex);
                        }
                    } else {
                        
                        JOptionPane.showMessageDialog(null,"INCORRECT CREDENTIALS","WARNING !!!",JOptionPane.WARNING_MESSAGE);

                    }
                    

                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Password", "Warning !!!", JOptionPane.WARNING_MESSAGE);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }

        }
    }//GEN-LAST:event_btnLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtAdminPass;
    private javax.swing.JTextField txtAdminUser;
    // End of variables declaration//GEN-END:variables
}
